create table PERSON_ITEM
(
    ID        BIGINT    NOT NULL    AUTO_INCREMENT,
    COUNT     BIGINT    NOT NULL ,
    PRICE     DOUBLE    NOT NULL ,
    ITEM_ID   BIGINT    NOT NULL ,
    PERSON_ID BIGINT    NOT NULL ,

    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_IN_PERSON_ITEM
        FOREIGN KEY (PERSON_ID) REFERENCES PERSON,
    CONSTRAINT FK_ITEM_IN_PERSON_ITEM
        FOREIGN KEY (ITEM_ID) REFERENCES ITEM
);

