### 랜덤 숫자 생성 API case 1
GET http://localhost:8080/api/v1/calculator/generate/1~22


### 랜덤 숫자 생성 API case 2
GET http://localhost:8080/api/v1/calculator/generate/0~100

### 랜덤 숫자 생성 API case 3
GET http://localhost:8080/api/v1/calculator/generate/1.5~100.1555

### 랜덤 숫자 생성 API case 4
GET http://localhost:8080/api/v1/calculator/generate/1.5~5.5

### 랜덤 숫자 생성 API case 5
GET http://localhost:8080/api/v1/calculator/generate/100.5111~1032.12
