GET localhost:8080/api/v1/simple/country/id/9
Accept: application/json

###
POST localhost:8080/api/v1/simple/company
Content-Type: application/json

{
  "name": "Apple",
  "founding_date": "2011-01-22",
  "country": "USA"
}

###
GET localhost:8080/api/v1/company/country/KOREA
Accept: application/json
