### case 1
POST http://localhost:8080/api/v1/calculator/calculate
Content-Type: application/json

{
  "expression": "1 + 5 * 10 - 10 / 10 ^ 5",
  "round": 4
}

### case 2
POST http://localhost:8080/api/v1/calculator/calculate
Content-Type: application/json

{
  "expression": "2 + 1 * 2 / 100 ^ 2",
  "round": 5
}

### case 3
POST http://localhost:8080/api/v1/calculator/calculate
Content-Type: application/json

{
  "expression": "940 + 519 ^ 2 - 579 * 108 ^ 2 / 749 + 1000 + 10",
  "round": 2
}
