CREATE TABLE COUNTRY
(
    ZIP_CODE        BIGINT          NOT NULL UNIQUE ,
    NAME            VARCHAR(45)     NOT NULL UNIQUE,
    CAPITAL_CITY    VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ZIP_CODE)
);