CREATE TABLE ITEM
(
    DTYPE    VARCHAR(31)    NOT NULL,
    ITEM_ID  BIGINT         NOT NULL    AUTO_INCREMENT,
    NAME     VARCHAR(255)   NOT NULL,
    PRICE    INTEGER        NOT NULL,
    QUANTITY INTEGER        NOT NULL,
    ARTIST   VARCHAR(255),
    AUTHOR   VARCHAR(255),
    ACTOR    VARCHAR(255),
    DIRECTOR VARCHAR(255),

    PRIMARY KEY (ITEM_ID)
);

